name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
    
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: test
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -coverprofile=coverage.out -covermode=atomic -cover -json -v ./... 2>&1 | go-junit-report -set-exit-code > tests.xml

      - name: fuzz
        run: go test -list . | grep Fuzz | xargs -P 8 -I {} go test -fuzz {} -fuzztime 5s .

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
