name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: get code
        uses: actions/checkout@v2

      - name: test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: fuzz
        run: go test -list . | grep Fuzz | xargs -P 8 -I {} go test -fuzz {} -fuzztime 10s .

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          verbose: true
