name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Fuzz
        run: |
          go test -fuzztime 5s -fuzz Fuzz_DeMorganLawsExtended ./...
          go test -fuzztime 5s -fuzz Fuzz_LogicOperationsWithAddition ./...
          go test -fuzztime 5s -fuzz Fuzz_InequalitiesAmongLogicAndArithmetic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          verbose: true
